In [4]:
%pip install pandas sqlalchemy psycopg2-binary pymongo python-dotenv

Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (2.3.3)
Requirement already satisfied: sqlalchemy in /opt/anaconda3/lib/python3.13/site-packages (2.0.43)
Requirement already satisfied: psycopg2-binary in /opt/anaconda3/lib/python3.13/site-packages (2.9.11)
Requirement already satisfied: pymongo in /opt/anaconda3/lib/python3.13/site-packages (4.16.0)
Requirement already satisfied: python-dotenv in /opt/anaconda3/lib/python3.13/site-packages (1.1.0)
Requirement already satisfied: numpy>=1.26.0 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/anaconda3/lib/python3.13/site-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: dnspython<3.0.0,>=2.6.1 in /opt/anaconda3/lib/python3.13/site-packages (from pymongo) (2.8.0)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [4]:
import pandas as pd

stores = pd.read_csv("stores.csv")
stores.head()

,store_id,store_name,address,borough,phone,opening_date,store_status
0,1,ABC Foodmart - Jackson Heights,"74-12 37th Avenue, Jackson Heights, NY 11372",Queens,718-555-0101,1996-04-15,Active
1,2,ABC Foodmart - Astoria,"31-18 Broadway, Astoria, NY 11106",Queens,718-555-0102,2004-09-01,Active
2,3,ABC Foodmart - Williamsburg,"185 Bedford Avenue, Brooklyn, NY 11211",Brooklyn,718-555-0103,2027-03-01,Planned
3,4,ABC Foodmart - Crown Heights,"820 Eastern Parkway, Brooklyn, NY 11213",Brooklyn,718-555-0104,2027-06-01,Planned
4,5,ABC Foodmart - Bay Ridge,"7420 5th Avenue, Brooklyn, NY 11209",Brooklyn,718-555-0105,2027-09-01,Planned

In [5]:
stores.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   store_id      5 non-null      int64
 1   store_name    5 non-null      object
 2   address       5 non-null      object
 3   borough       5 non-null      object
 4   phone         5 non-null      object
 5   opening_date  5 non-null      object
 6   store_status  5 non-null      object
dtypes: int64(1), object(6)
memory usage: 412.0+ bytes

In [7]:
stores_clean = stores.copy()

# Clean text fields: remove accidental spaces before or after the value
text_columns = ["store_name", "address", "borough", "phone", "store_status"]

for column in text_columns:
    stores_clean[column] = stores_clean[column].astype("string").str.strip()

# Convert opening_date from text to a real date value
stores_clean["opening_date"] = pd.to_datetime(
    stores_clean["opening_date"],
    format="%Y-%m-%d",
    errors="coerce"
)

stores_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   store_id      5 non-null      int64
 1   store_name    5 non-null      string
 2   address       5 non-null      string
 3   borough       5 non-null      string
 4   phone         5 non-null      string
 5   opening_date  5 non-null      datetime64[ns]
 6   store_status  5 non-null      string
dtypes: datetime64[ns](1), int64(1), string(5)
memory usage: 412.0 bytes

Stores ETL validation passed.

,store_id,store_name,address,borough,phone,opening_date,store_status
0,1,ABC Foodmart - Jackson Heights,"74-12 37th Avenue, Jackson Heights, NY 11372",Queens,718-555-0101,1996-04-15,Active
1,2,ABC Foodmart - Astoria,"31-18 Broadway, Astoria, NY 11106",Queens,718-555-0102,2004-09-01,Active
2,3,ABC Foodmart - Williamsburg,"185 Bedford Avenue, Brooklyn, NY 11211",Brooklyn,718-555-0103,2027-03-01,Planned
3,4,ABC Foodmart - Crown Heights,"820 Eastern Parkway, Brooklyn, NY 11213",Brooklyn,718-555-0104,2027-06-01,Planned
4,5,ABC Foodmart - Bay Ridge,"7420 5th Avenue, Brooklyn, NY 11209",Brooklyn,718-555-0105,2027-09-01,Planned

In [9]:
valid_statuses = {"Active", "Planned", "Closed"}
valid_boroughs = {"Queens", "Brooklyn"}

assert stores_clean["store_id"].notna().all(), "store_id contains missing values"
assert stores_clean["store_id"].is_unique, "store_id contains duplicates"
assert stores_clean["opening_date"].notna().all(), "opening_date contains invalid dates"
assert stores_clean["store_status"].isin(valid_statuses).all(), "invalid store_status found"
assert stores_clean["borough"].isin(valid_boroughs).all(), "invalid borough found"

print("Stores ETL validation passed.")
display(stores_clean)

Stores ETL validation passed.

,store_id,store_name,address,borough,phone,opening_date,store_status
0,1,ABC Foodmart - Jackson Heights,"74-12 37th Avenue, Jackson Heights, NY 11372",Queens,718-555-0101,1996-04-15,Active
1,2,ABC Foodmart - Astoria,"31-18 Broadway, Astoria, NY 11106",Queens,718-555-0102,2004-09-01,Active
2,3,ABC Foodmart - Williamsburg,"185 Bedford Avenue, Brooklyn, NY 11211",Brooklyn,718-555-0103,2027-03-01,Planned
3,4,ABC Foodmart - Crown Heights,"820 Eastern Parkway, Brooklyn, NY 11213",Brooklyn,718-555-0104,2027-06-01,Planned
4,5,ABC Foodmart - Bay Ridge,"7420 5th Avenue, Brooklyn, NY 11209",Brooklyn,718-555-0105,2027-09-01,Planned

In [10]:
!docker ps

CONTAINER ID   IMAGE      COMMAND                  CREATED        STATUS       PORTS                                  NAMES
1be82e2aafef   mongo      "docker-entrypoint.s…"   3 months ago   Up 6 hours   0.0.0.0:27017-27019->27017-27019/tcp   mongodb
1b27f8edcdb6   postgres   "docker-entrypoint.s…"   3 months ago   Up 6 hours   0.0.0.0:5432->5432/tcp                 postgres

In [12]:
%pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /opt/anaconda3/lib/python3.13/site-packages (2.0.43)
Requirement already satisfied: psycopg2-binary in /opt/anaconda3/lib/python3.13/site-packages (2.9.11)
Requirement already satisfied: typing-extensions>=4.6.0 in /opt/anaconda3/lib/python3.13/site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [13]:
from sqlalchemy import create_engine, text

admin_engine = create_engine(
    "postgresql+psycopg2://postgres:123@localhost:5432/postgres"
)

with admin_engine.connect() as conn:
    result = conn.execute(
        text("SELECT current_database(), version();")
    ).one()

print(result)

('postgres', 'PostgreSQL 18.3 (Debian 18.3-1.pgdg13+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 14.2.0-19) 14.2.0, 64-bit')

In [14]:
from sqlalchemy import create_engine, text

FOODMART_DB = "abc_foodmart"

admin_engine = create_engine(
    "postgresql+psycopg2://postgres:123@localhost:5432/postgres",
    isolation_level="AUTOCOMMIT"
)

with admin_engine.connect() as conn:
    database_exists = conn.execute(
        text("SELECT 1 FROM pg_database WHERE datname = :db_name"),
        {"db_name": FOODMART_DB}
    ).scalar()

    if database_exists:
        print("abc_foodmart already exists.")
    else:
        conn.execute(text("CREATE DATABASE abc_foodmart"))
        print("abc_foodmart created successfully.")

abc_foodmart created successfully.

In [15]:
pg_engine = create_engine(
    "postgresql+psycopg2://postgres:123@localhost:5432/abc_foodmart"
)

with pg_engine.connect() as conn:
    print(conn.execute(text("SELECT current_database();")).scalar())

abc_foodmart

In [18]:
from pathlib import Path

matches = list(Path("/Users/cynthia").rglob("Group2_CP3_sqlcode.sql"))

for path in matches:
    print(path)

/Users/cynthia/Desktop/Group2_CP3_sqlcode.sql
/Users/cynthia/.Trash/Group2_CP3_sqlcode.sql

In [19]:
schema_path = Path("/Users/cynthia/Desktop/Group2_CP3_sqlcode.sql")
schema_sql = schema_path.read_text(encoding="utf-8")

print("CREATE TABLE count:", schema_sql.count("CREATE TABLE"))
print("vendor_products present:", "vendor_products" in schema_sql)

CREATE TABLE count: 18
vendor_products present: False

In [20]:
with pg_engine.begin() as conn:
    conn.exec_driver_sql(schema_sql)

print("18 empty tables created in abc_foodmart.")

18 empty tables created in abc_foodmart.

In [21]:
stores_for_pg = stores_clean.copy()

# PostgreSQL 的 DATE 字段只需要日期，不需要 pandas 的时间部分
stores_for_pg["opening_date"] = stores_for_pg["opening_date"].dt.date

stores_for_pg.to_sql(
    name="stores",
    con=pg_engine,
    if_exists="append",
    index=False,
    method="multi"
)

print(f"{len(stores_for_pg)} stores loaded into PostgreSQL.")

5 stores loaded into PostgreSQL.

In [22]:
with pg_engine.connect() as conn:
    stores_in_pg = pd.read_sql(
        text("""
            SELECT store_id, store_name, borough, opening_date, store_status
            FROM stores
            ORDER BY store_id;
        """),
        conn
    )

display(stores_in_pg)

,store_id,store_name,borough,opening_date,store_status
0,1,ABC Foodmart - Jackson Heights,Queens,1996-04-15,Active
1,2,ABC Foodmart - Astoria,Queens,2004-09-01,Active
2,3,ABC Foodmart - Williamsburg,Brooklyn,2027-03-01,Planned
3,4,ABC Foodmart - Crown Heights,Brooklyn,2027-06-01,Planned
4,5,ABC Foodmart - Bay Ridge,Brooklyn,2027-09-01,Planned

In [23]:
positions = pd.read_csv("positions.csv")
positions.head()

   position_id              position_title  hourly_rate
0            1               Store Manager           32
1            2          Department Manager           25
2            3                     Cashier           19
3            4             Stock Associate           20
4            5  Customer Service Associate           21

In [24]:
positions_clean = positions.copy()

positions_clean["position_title"] = (
    positions_clean["position_title"]
    .astype("string")
    .str.strip()
)

positions_clean["hourly_rate"] = pd.to_numeric(
    positions_clean["hourly_rate"],
    errors="coerce"
)

assert positions_clean["position_id"].notna().all()
assert positions_clean["position_id"].is_unique
assert positions_clean["position_title"].notna().all()
assert positions_clean["position_title"].is_unique
assert positions_clean["hourly_rate"].notna().all()
assert (positions_clean["hourly_rate"] >= 0).all()

print("Positions ETL validation passed.")

Positions ETL validation passed.

In [25]:
positions_clean.to_sql(
    "positions",
    pg_engine,
    if_exists="append",
    index=False,
    method="multi"
)

print("Positions loaded into PostgreSQL.")

Positions loaded into PostgreSQL.

In [26]:
pd.read_sql(
    "SELECT * FROM positions ORDER BY position_id;",
    pg_engine
)

   position_id              position_title  hourly_rate
0            1               Store Manager         32.0
1            2          Department Manager         25.0
2            3                     Cashier         19.0
3            4             Stock Associate         20.0
4            5  Customer Service Associate         21.0
5            6             Receiving Clerk         22.0

In [27]:
vendors = pd.read_csv("vendors.csv")

vendors_clean = vendors.copy()

for column in ["vendor_name", "contact_name", "contact_phone", "vendor_status"]:
    vendors_clean[column] = (
        vendors_clean[column]
        .astype("string")
        .str.strip()
    )

# The PostgreSQL schema requires ACTIVE or INACTIVE
vendors_clean["vendor_status"] = vendors_clean["vendor_status"].str.upper()

assert vendors_clean["vendor_id"].notna().all()
assert vendors_clean["vendor_id"].is_unique
assert vendors_clean["vendor_name"].notna().all()
assert vendors_clean["vendor_status"].isin({"ACTIVE", "INACTIVE"}).all()

vendors_clean.to_sql(
    "vendors",
    pg_engine,
    if_exists="append",
    index=False,
    method="multi"
)

print(f"{len(vendors_clean)} vendors loaded into PostgreSQL.")

vendors_in_pg = pd.read_sql(
    "SELECT * FROM vendors ORDER BY vendor_id;",
    pg_engine
)

display(vendors_in_pg)

7 vendors loaded into PostgreSQL.

,vendor_id,vendor_name,contact_name,contact_phone,vendor_status
0,1,Danone Distribution,Purchasing Desk,212-555-2001,ACTIVE
1,2,G&G Distribution,Purchasing Desk,212-555-2002,ACTIVE
2,3,General Farms Distribution,Purchasing Desk,212-555-2003,ACTIVE
3,4,MG Distribution,Purchasing Desk,212-555-2004,ACTIVE
4,5,Montanella Distribution,Purchasing Desk,212-555-2005,ACTIVE
5,6,Pampers Distribution,Purchasing Desk,212-555-2006,ACTIVE
6,7,Roberto Distribution,Purchasing Desk,212-555-2007,ACTIVE

In [28]:
customers = pd.read_csv("customers.csv")

customers_clean = customers.copy()

# Clean text fields
for column in [
    "first_name", "last_name", "phone", "email",
    "loyalty_number", "loyalty_status"
]:
    customers_clean[column] = (
        customers_clean[column]
        .astype("string")
        .str.strip()
    )

# Standardize emails and convert the date
customers_clean["email"] = customers_clean["email"].str.lower()

customers_clean["created_date"] = pd.to_datetime(
    customers_clean["created_date"],
    format="%Y-%m-%d",
    errors="coerce"
)

# Validate against the schema rules
assert customers_clean["customer_id"].notna().all()
assert customers_clean["customer_id"].is_unique
assert customers_clean["first_name"].notna().all()
assert customers_clean["last_name"].notna().all()
assert customers_clean["created_date"].notna().all()
assert customers_clean["loyalty_status"].isin(
    {"Non-Member", "Active", "Inactive"}
).all()

# Convert pandas date to PostgreSQL DATE
customers_clean["created_date"] = customers_clean["created_date"].dt.date

# Load into PostgreSQL
customers_clean.to_sql(
    "customers",
    pg_engine,
    if_exists="append",
    index=False,
    method="multi"
)

print(f"{len(customers_clean)} customers loaded into PostgreSQL.")

# Verify
customers_in_pg = pd.read_sql(
    """
    SELECT customer_id, first_name, last_name, loyalty_number,
           loyalty_status, created_date
    FROM customers
    ORDER BY customer_id;
    """,
    pg_engine
)

display(customers_in_pg.head(10))

500 customers loaded into PostgreSQL.

   customer_id first_name last_name loyalty_number loyalty_status created_date
0            1      Ellis      Kirk       LOY00001         Active   2019-05-06
1            2    Belinda   Johnson       LOY00002         Active   2017-03-05
2            3     Joelle      Beck       LOY00003         Active   2015-04-27
3            4      Kevin    Mccabe       LOY00004         Active   2018-08-01
4            5     Scotty    Armour       LOY00005         Active   2018-10-29
5            6      Sally  Mitchell       LOY00006         Active   2019-11-06
6            7      Janet    Spears       LOY00007         Active   2020-05-03
7            8    Jessica     Ralph       LOY00008         Active   2016-06-01
8            9    Timothy      Head       LOY00009         Active   2016-01-10
9           10      David     Smith       LOY00010         Active   2019-07-12

In [29]:
departments = pd.read_csv("departments.csv")

departments_clean = departments.copy()

departments_clean["department_name"] = (
    departments_clean["department_name"]
    .astype("string")
    .str.strip()
)

# Validate primary key, foreign key, and unique department names per store
assert departments_clean["department_id"].notna().all()
assert departments_clean["department_id"].is_unique
assert departments_clean["store_id"].isin(stores_clean["store_id"]).all()
assert departments_clean["department_name"].notna().all()

assert not departments_clean.duplicated(
    subset=["store_id", "department_name"]
).any()

departments_clean.to_sql(
    "departments",
    pg_engine,
    if_exists="append",
    index=False,
    method="multi"
)

print(f"{len(departments_clean)} departments loaded into PostgreSQL.")

pd.read_sql(
    """
    SELECT d.department_id, s.store_name, d.department_name
    FROM departments d
    JOIN stores s ON d.store_id = s.store_id
    ORDER BY d.department_id;
    """,
    pg_engine
)

20 departments loaded into PostgreSQL.

    department_id                      store_name   department_name
0               1  ABC Foodmart - Jackson Heights           Grocery
1               2  ABC Foodmart - Jackson Heights           Produce
2               3  ABC Foodmart - Jackson Heights          Checkout
3               4  ABC Foodmart - Jackson Heights  Customer Service
4               5          ABC Foodmart - Astoria           Grocery
5               6          ABC Foodmart - Astoria           Produce
6               7          ABC Foodmart - Astoria          Checkout
7               8          ABC Foodmart - Astoria  Customer Service
8               9     ABC Foodmart - Williamsburg           Grocery
9              10     ABC Foodmart - Williamsburg           Produce
10             11     ABC Foodmart - Williamsburg          Checkout
11             12     ABC Foodmart - Williamsburg  Customer Service
12             13    ABC Foodmart - Crown Heights           Grocery
13             14    ABC Foodmart - Crown Heights           Produce
14             15    ABC Foodmart - Crown Heights          Checkout
15             16    ABC Foodmart - Crown Heights  Customer Service
16             17        ABC Foodmart - Bay Ridge           Grocery
17             18        ABC Foodmart - Bay Ridge           Produce
18             19        ABC Foodmart - Bay Ridge          Checkout
19             20        ABC Foodmart - Bay Ridge  Customer Service

In [30]:
products = pd.read_csv("products.csv")

products_clean = products.copy()

for column in ["product_name", "category", "measure_unit", "product_status"]:
    products_clean[column] = (
        products_clean[column]
        .astype("string")
        .str.strip()
    )

products_clean["product_status"] = products_clean["product_status"].str.upper()

products_clean["selling_price"] = pd.to_numeric(
    products_clean["selling_price"],
    errors="coerce"
)

valid_vendor_ids = set(
    pd.read_sql("SELECT vendor_id FROM vendors;", pg_engine)["vendor_id"]
)

assert products_clean["product_id"].notna().all()
assert products_clean["product_id"].is_unique
assert products_clean["vendor_id"].isin(valid_vendor_ids).all()
assert products_clean["product_name"].notna().all()
assert products_clean["selling_price"].notna().all()
assert (products_clean["selling_price"] >= 0).all()
assert products_clean["product_status"].isin(
    {"ACTIVE", "INACTIVE", "DISCONTINUED"}
).all()

products_clean.to_sql(
    "products",
    pg_engine,
    if_exists="append",
    index=False,
    method="multi"
)

print(f"{len(products_clean)} products loaded into PostgreSQL.")

pd.read_sql(
    """
    SELECT p.product_id, p.product_name, p.category,
           v.vendor_name, p.selling_price, p.product_status
    FROM products p
    JOIN vendors v ON p.vendor_id = v.vendor_id
    ORDER BY p.product_id;
    """,
    pg_engine
)

30 products loaded into PostgreSQL.

,product_id,product_name,category,vendor_name,selling_price,product_status
0,1,"PAMPERS BABY DRY PANTS SIZE 4 x72/Pack, 8-20kg...",Baby,Pampers Distribution,9.99,ACTIVE
1,2,PAMPERS SENSITIVE PROTECT WIPES PACK OF 280pcs,Baby,Pampers Distribution,4.21,ACTIVE
2,3,Reusable Shopping Bags 5 Count,Household,G&G Distribution,4.99,ACTIVE
3,4,Aluminum Foil 75 sq ft,Household,G&G Distribution,5.49,ACTIVE
4,5,PORK RIBS FRESH FREE RANGE BY MONTANELLA 380g,Meat,Montanella Distribution,6.20,ACTIVE
5,6,CHICKEN THIGH 400g,Meat,General Farms Distribution,7.00,ACTIVE
6,7,BEEF FILLET Steak Organic 500g,Meat,General Farms Distribution,10.30,ACTIVE
7,8,NATURAL WHOLE YOGURT WITH STRAWBERRIES PACK OF 6,Chilled,G&G Distribution,4.00,ACTIVE
8,9,DANONE SIMPLY FRUIT STRABERRY 4x125g,Chilled,Danone Distribution,5.00,ACTIVE
9,10,ROBERTO PANE INTEGRALE 400g,Bakery,Roberto Distribution,1.50,ACTIVE
10,11,Organic Bananas,Produce,General Farms Distribution,0.79,ACTIVE
11,12,Gala Apples,Produce,General Farms Distribution,1.49,ACTIVE
12,13,Whole Milk 1 Gallon,Dairy,G&G Distribution,4.69,ACTIVE
13,14,Large Eggs 12 Count,Dairy,G&G Distribution,4.29,ACTIVE
14,15,Long Grain Rice 5 lb,Grocery,G&G Distribution,7.99,ACTIVE
15,16,Black Beans 15 oz,Grocery,G&G Distribution,1.29,ACTIVE
16,17,Olive Oil 1 Liter,Grocery,Montanella Distribution,12.99,ACTIVE
17,18,Sparkling Water 12 Pack,Beverages,G&G Distribution,6.99,ACTIVE
18,19,Orange Juice 64 oz,Beverages,General Farms Distribution,5.49,ACTIVE
19,20,Paper Towels 6 Roll,Household,G&G Distribution,9.99,ACTIVE
20,21,Dish Soap 24 oz,Household,G&G Distribution,3.99,ACTIVE
21,22,Laundry Detergent 64 oz,Household,G&G Distribution,11.49,ACTIVE
22,23,Whole Wheat Bread,Bakery,Roberto Distribution,3.49,ACTIVE
23,24,Bagels 6 Count,Bakery,Roberto Distribution,4.99,ACTIVE
24,25,Ground Coffee 12 oz,Beverages,G&G Distribution,9.49,ACTIVE
25,26,Chicken Breast 1 lb,Meat,General Farms Distribution,6.99,ACTIVE
26,27,Ground Beef 1 lb,Meat,General Farms Distribution,7.49,ACTIVE
27,28,Cheddar Cheese 8 oz,Dairy,G&G Distribution,4.79,ACTIVE
28,29,Frozen Mixed Vegetables,Frozen,G&G Distribution,3.49,ACTIVE
29,30,Vanilla Ice Cream 1.5 qt,Frozen,G&G Distribution,6.49,ACTIVE

In [31]:
employees = pd.read_csv("employees.csv")
employees_clean = employees.copy()

for column in ["first_name", "last_name", "employment_type", "employee_status"]:
    employees_clean[column] = (
        employees_clean[column]
        .astype("string")
        .str.strip()
    )

employees_clean["hire_date"] = pd.to_datetime(
    employees_clean["hire_date"],
    format="%Y-%m-%d",
    errors="coerce"
)

# Validate IDs against the tables already in PostgreSQL
valid_department_ids = set(
    pd.read_sql("SELECT department_id FROM departments;", pg_engine)["department_id"]
)

valid_position_ids = set(
    pd.read_sql("SELECT position_id FROM positions;", pg_engine)["position_id"]
)

department_store_lookup = pd.read_sql(
    "SELECT department_id, store_id AS department_store_id FROM departments;",
    pg_engine
)

employee_check = employees_clean.merge(
    department_store_lookup,
    on="department_id",
    how="left"
)

assert employees_clean["employee_id"].notna().all()
assert employees_clean["employee_id"].is_unique
assert employees_clean["department_id"].isin(valid_department_ids).all()
assert employees_clean["position_id"].isin(valid_position_ids).all()
assert employees_clean["hire_date"].notna().all()
assert employees_clean["employment_type"].isin({"Full-Time", "Part-Time"}).all()
assert employees_clean["employee_status"].isin(
    {"Active", "Inactive", "Terminated"}
).all()

# Confirm the CSV's store_id agrees with the store of that employee's department
assert employee_check["department_store_id"].notna().all()
assert (
    employee_check["store_id"] == employee_check["department_store_id"]
).all(), "Employee store_id conflicts with department store_id."

# store_id is redundant in the final 3NF employees table
employees_for_pg = employees_clean.drop(columns=["store_id"])
employees_for_pg["hire_date"] = employees_for_pg["hire_date"].dt.date

employees_for_pg.to_sql(
    "employees",
    pg_engine,
    if_exists="append",
    index=False,
    method="multi"
)

print(f"{len(employees_for_pg)} employees loaded into PostgreSQL.")

50 employees loaded into PostgreSQL.

In [32]:
employee_shifts = pd.read_csv("employee_shifts.csv")
employee_shifts_clean = employee_shifts.copy()

employee_shifts_clean["shift_status"] = (
    employee_shifts_clean["shift_status"]
    .astype("string")
    .str.strip()
    .str.lower()
    .map({
        "scheduled": "Scheduled",
        "completed": "Completed",
        "absent": "Absent",
        "cancelled": "Cancelled"
    })
)

for column in ["shift_start", "shift_end"]:
    employee_shifts_clean[column] = pd.to_datetime(
        employee_shifts_clean[column],
        errors="coerce"
    )

valid_employee_ids = set(
    pd.read_sql("SELECT employee_id FROM employees;", pg_engine)["employee_id"]
)

assert employee_shifts_clean["shift_id"].notna().all()
assert employee_shifts_clean["shift_id"].is_unique
assert employee_shifts_clean["employee_id"].isin(valid_employee_ids).all()
assert employee_shifts_clean["shift_start"].notna().all()
assert employee_shifts_clean["shift_end"].notna().all()
assert (employee_shifts_clean["shift_end"] > employee_shifts_clean["shift_start"]).all()
assert employee_shifts_clean["shift_status"].isin(
    {"Scheduled", "Completed", "Absent", "Cancelled"}
).all()

assert not employee_shifts_clean.duplicated(
    subset=["employee_id", "shift_start"]
).any()

employee_shifts_clean.to_sql(
    "employee_shifts",
    pg_engine,
    if_exists="append",
    index=False,
    method="multi"
)

print(f"{len(employee_shifts_clean)} employee shifts loaded into PostgreSQL.")

100 employee shifts loaded into PostgreSQL.

In [33]:
pd.read_sql(
    """
    SELECT es.shift_id, e.first_name, e.last_name,
           es.shift_start, es.shift_end, es.shift_status
    FROM employee_shifts es
    JOIN employees e ON es.employee_id = e.employee_id
    ORDER BY es.shift_id;
    """,
    pg_engine
).head(10)

,shift_id,first_name,last_name,shift_start,shift_end,shift_status
0,1,Ethan,Lopez,2026-08-10 10:00:00,2026-08-10 18:00:00,Scheduled
1,2,Ethan,Lopez,2026-08-11 10:00:00,2026-08-11 18:00:00,Scheduled
2,3,Harper,Clark,2026-08-10 12:00:00,2026-08-10 20:00:00,Scheduled
3,4,Harper,Clark,2026-08-11 12:00:00,2026-08-11 20:00:00,Scheduled
4,5,Daniel,Singh,2026-08-10 08:00:00,2026-08-10 16:00:00,Scheduled
5,6,Daniel,Singh,2026-08-11 08:00:00,2026-08-11 16:00:00,Scheduled
6,7,Zoe,White,2026-08-10 10:00:00,2026-08-10 18:00:00,Scheduled
7,8,Zoe,White,2026-08-11 10:00:00,2026-08-11 18:00:00,Scheduled
8,9,Julian,Kim,2026-08-10 12:00:00,2026-08-10 20:00:00,Scheduled
9,10,Julian,Kim,2026-08-11 12:00:00,2026-08-11 20:00:00,Scheduled

In [34]:
time_off_records = pd.read_csv("time_off_records.csv")
time_off_clean = time_off_records.copy()

for column in ["time_off_start", "time_off_end"]:
    time_off_clean[column] = pd.to_datetime(
        time_off_clean[column],
        errors="coerce"
    )

valid_employee_ids = set(
    pd.read_sql("SELECT employee_id FROM employees;", pg_engine)["employee_id"]
)

assert time_off_clean["time_off_id"].notna().all()
assert time_off_clean["time_off_id"].is_unique
assert time_off_clean["employee_id"].isin(valid_employee_ids).all()
assert time_off_clean["time_off_start"].notna().all()
assert time_off_clean["time_off_end"].notna().all()
assert (
    time_off_clean["time_off_end"] > time_off_clean["time_off_start"]
).all()

assert not time_off_clean.duplicated(
    subset=["employee_id", "time_off_start", "time_off_end"]
).any()

time_off_clean.to_sql(
    "time_off_records",
    pg_engine,
    if_exists="append",
    index=False,
    method="multi"
)

print(f"{len(time_off_clean)} time-off records loaded into PostgreSQL.")

10 time-off records loaded into PostgreSQL.

In [35]:
pd.read_sql(
    """
    SELECT t.time_off_id, e.first_name, e.last_name,
           t.time_off_start, t.time_off_end
    FROM time_off_records t
    JOIN employees e ON t.employee_id = e.employee_id
    ORDER BY t.time_off_id;
    """,
    pg_engine
)

   time_off_id first_name last_name      time_off_start        time_off_end
0            1     Harper     Clark 2026-09-02 09:00:00 2026-09-03 09:00:00
1            2        Zoe     White 2026-09-03 09:00:00 2026-09-04 09:00:00
2            3        Ava    Thomas 2026-09-04 09:00:00 2026-09-05 09:00:00
3            4     Harper    Wilson 2026-09-05 09:00:00 2026-09-06 09:00:00
4            5        Zoe     Davis 2026-09-06 09:00:00 2026-09-07 09:00:00
5            6        Ava     Brown 2026-09-07 09:00:00 2026-09-08 09:00:00
6            7     Harper  Martinez 2026-09-08 09:00:00 2026-09-09 09:00:00
7            8        Zoe    Garcia 2026-09-09 09:00:00 2026-09-10 09:00:00
8            9        Ava   Johnson 2026-09-10 09:00:00 2026-09-11 09:00:00
9           10     Harper    Rivera 2026-09-11 09:00:00 2026-09-12 09:00:00

In [36]:
purchase_orders = pd.read_csv("purchase_orders.csv")
purchase_orders_clean = purchase_orders.copy()

purchase_orders_clean["order_status"] = (
    purchase_orders_clean["order_status"]
    .astype("string")
    .str.strip()
    .str.upper()
)

for column in ["order_date", "expected_delivery_date"]:
    purchase_orders_clean[column] = pd.to_datetime(
        purchase_orders_clean[column],
        errors="coerce"
    )

valid_vendor_ids = set(
    pd.read_sql("SELECT vendor_id FROM vendors;", pg_engine)["vendor_id"]
)

valid_store_ids = set(
    pd.read_sql("SELECT store_id FROM stores;", pg_engine)["store_id"]
)

assert purchase_orders_clean["purchase_order_id"].notna().all()
assert purchase_orders_clean["purchase_order_id"].is_unique
assert purchase_orders_clean["vendor_id"].isin(valid_vendor_ids).all()
assert purchase_orders_clean["store_id"].isin(valid_store_ids).all()
assert purchase_orders_clean["order_date"].notna().all()

assert purchase_orders_clean["order_status"].isin({
    "DRAFT", "SUBMITTED", "APPROVED",
    "PARTIALLY_RECEIVED", "RECEIVED", "CANCELLED"
}).all()

assert (
    purchase_orders_clean["expected_delivery_date"].isna()
    | (
        purchase_orders_clean["expected_delivery_date"]
        >= purchase_orders_clean["order_date"]
    )
).all()

for column in ["order_date", "expected_delivery_date"]:
    purchase_orders_clean[column] = purchase_orders_clean[column].dt.date

purchase_orders_clean.to_sql(
    "purchase_orders",
    pg_engine,
    if_exists="append",
    index=False,
    method="multi"
)

print(f"{len(purchase_orders_clean)} purchase orders loaded into PostgreSQL.")

20 purchase orders loaded into PostgreSQL.

In [37]:
pd.read_sql(
    """
    SELECT po.purchase_order_id, v.vendor_name, s.store_name,
           po.order_date, po.order_status, po.expected_delivery_date
    FROM purchase_orders po
    JOIN vendors v ON po.vendor_id = v.vendor_id
    JOIN stores s ON po.store_id = s.store_id
    ORDER BY po.purchase_order_id;
    """,
    pg_engine
)

,purchase_order_id,vendor_name,store_name,order_date,order_status,expected_delivery_date
0,1,Danone Distribution,ABC Foodmart - Jackson Heights,2026-05-05,RECEIVED,2026-05-10
1,2,G&G Distribution,ABC Foodmart - Astoria,2026-05-09,PARTIALLY_RECEIVED,2026-05-14
2,3,General Farms Distribution,ABC Foodmart - Jackson Heights,2026-05-13,APPROVED,2026-05-18
3,4,MG Distribution,ABC Foodmart - Astoria,2026-05-17,RECEIVED,2026-05-22
4,5,Montanella Distribution,ABC Foodmart - Jackson Heights,2026-05-21,RECEIVED,2026-05-26
5,6,Pampers Distribution,ABC Foodmart - Astoria,2026-05-25,PARTIALLY_RECEIVED,2026-05-30
6,7,Roberto Distribution,ABC Foodmart - Jackson Heights,2026-05-29,APPROVED,2026-06-03
7,8,Danone Distribution,ABC Foodmart - Astoria,2026-06-02,RECEIVED,2026-06-07
8,9,G&G Distribution,ABC Foodmart - Jackson Heights,2026-06-06,RECEIVED,2026-06-11
9,10,General Farms Distribution,ABC Foodmart - Astoria,2026-06-10,PARTIALLY_RECEIVED,2026-06-15
10,11,MG Distribution,ABC Foodmart - Jackson Heights,2026-06-14,APPROVED,2026-06-19
11,12,Montanella Distribution,ABC Foodmart - Astoria,2026-06-18,RECEIVED,2026-06-23
12,13,Pampers Distribution,ABC Foodmart - Jackson Heights,2026-06-22,RECEIVED,2026-06-27
13,14,Roberto Distribution,ABC Foodmart - Astoria,2026-06-26,PARTIALLY_RECEIVED,2026-07-01
14,15,Danone Distribution,ABC Foodmart - Jackson Heights,2026-06-30,APPROVED,2026-07-05
15,16,G&G Distribution,ABC Foodmart - Astoria,2026-07-04,RECEIVED,2026-07-09
16,17,General Farms Distribution,ABC Foodmart - Jackson Heights,2026-07-08,RECEIVED,2026-07-13
17,18,MG Distribution,ABC Foodmart - Astoria,2026-07-12,PARTIALLY_RECEIVED,2026-07-17
18,19,Montanella Distribution,ABC Foodmart - Jackson Heights,2026-07-16,APPROVED,2026-07-21
19,20,Pampers Distribution,ABC Foodmart - Astoria,2026-07-20,RECEIVED,2026-07-25

In [38]:
import numpy as np

purchase_order_items = pd.read_csv("purchase_order_items.csv")
po_items_clean = purchase_order_items.copy()

for column in ["order_quantity", "unit_cost", "line_total"]:
    po_items_clean[column] = pd.to_numeric(
        po_items_clean[column],
        errors="coerce"
    )

valid_po_ids = set(
    pd.read_sql(
        "SELECT purchase_order_id FROM purchase_orders;",
        pg_engine
    )["purchase_order_id"]
)

valid_product_ids = set(
    pd.read_sql(
        "SELECT product_id FROM products;",
        pg_engine
    )["product_id"]
)

assert po_items_clean["purchase_order_item_id"].notna().all()
assert po_items_clean["purchase_order_item_id"].is_unique
assert po_items_clean["purchase_order_id"].isin(valid_po_ids).all()
assert po_items_clean["product_id"].isin(valid_product_ids).all()
assert po_items_clean["order_quantity"].notna().all()
assert po_items_clean["unit_cost"].notna().all()
assert po_items_clean["line_total"].notna().all()

assert (po_items_clean["order_quantity"] > 0).all()
assert (po_items_clean["unit_cost"] >= 0).all()
assert (po_items_clean["line_total"] >= 0).all()

# Check: line_total = order_quantity × unit_cost
assert np.isclose(
    po_items_clean["line_total"],
    po_items_clean["order_quantity"] * po_items_clean["unit_cost"],
    atol=0.01
).all()

assert not po_items_clean.duplicated(
    subset=["purchase_order_id", "product_id"]
).any()

po_items_clean.to_sql(
    "purchase_order_items",
    pg_engine,
    if_exists="append",
    index=False,
    method="multi"
)

print(f"{len(po_items_clean)} purchase-order items loaded into PostgreSQL.")

39 purchase-order items loaded into PostgreSQL.

In [39]:
pd.read_sql(
    """
    SELECT poi.purchase_order_item_id, poi.purchase_order_id,
           p.product_name, poi.order_quantity,
           poi.unit_cost, poi.line_total
    FROM purchase_order_items poi
    JOIN products p ON poi.product_id = p.product_id
    ORDER BY poi.purchase_order_item_id;
    """,
    pg_engine
)

,purchase_order_item_id,purchase_order_id,product_name,order_quantity,unit_cost,line_total
0,1,1,DANONE SIMPLY FRUIT STRABERRY 4x125g,19.0,3.00,57.00
1,2,2,Reusable Shopping Bags 5 Count,41.0,2.30,94.30
2,3,2,Aluminum Foil 75 sq ft,33.0,3.10,102.30
3,4,2,NATURAL WHOLE YOGURT WITH STRAWBERRIES PACK OF 6,59.0,0.70,41.30
4,5,3,CHICKEN THIGH 400g,60.0,4.57,274.20
5,6,3,BEEF FILLET Steak Organic 500g,36.0,5.32,191.52
6,7,3,Organic Bananas,56.0,0.38,21.28
7,8,5,PORK RIBS FRESH FREE RANGE BY MONTANELLA 380g,32.0,4.58,146.56
8,9,5,Olive Oil 1 Liter,12.0,7.40,88.80
9,10,6,"PAMPERS BABY DRY PANTS SIZE 4 x72/Pack, 8-20kg...",30.0,4.88,146.40
10,11,6,PAMPERS SENSITIVE PROTECT WIPES PACK OF 280pcs,53.0,2.24,118.72
11,12,7,ROBERTO PANE INTEGRALE 400g,53.0,0.40,21.20
12,13,7,Whole Wheat Bread,15.0,1.55,23.25
13,14,7,Bagels 6 Count,57.0,2.30,131.10
14,15,8,DANONE SIMPLY FRUIT STRABERRY 4x125g,49.0,3.00,147.00
15,16,9,Reusable Shopping Bags 5 Count,44.0,2.30,101.20
16,17,9,Aluminum Foil 75 sq ft,17.0,3.10,52.70
17,18,9,NATURAL WHOLE YOGURT WITH STRAWBERRIES PACK OF 6,42.0,0.70,29.40
18,19,10,CHICKEN THIGH 400g,48.0,4.57,219.36
19,20,10,BEEF FILLET Steak Organic 500g,46.0,5.32,244.72
20,21,10,Organic Bananas,41.0,0.38,15.58
21,22,12,PORK RIBS FRESH FREE RANGE BY MONTANELLA 380g,34.0,4.58,155.72
22,23,12,Olive Oil 1 Liter,49.0,7.40,362.60
23,24,13,"PAMPERS BABY DRY PANTS SIZE 4 x72/Pack, 8-20kg...",57.0,4.88,278.16
24,25,13,PAMPERS SENSITIVE PROTECT WIPES PACK OF 280pcs,16.0,2.24,35.84
25,26,14,ROBERTO PANE INTEGRALE 400g,20.0,0.40,8.00
26,27,14,Whole Wheat Bread,52.0,1.55,80.60
27,28,14,Bagels 6 Count,39.0,2.30,89.70
28,29,15,DANONE SIMPLY FRUIT STRABERRY 4x125g,24.0,3.00,72.00
29,30,16,Reusable Shopping Bags 5 Count,50.0,2.30,115.00
30,31,16,Aluminum Foil 75 sq ft,60.0,3.10,186.00
31,32,16,NATURAL WHOLE YOGURT WITH STRAWBERRIES PACK OF 6,20.0,0.70,14.00
32,33,17,CHICKEN THIGH 400g,40.0,4.57,182.80
33,34,17,BEEF FILLET Steak Organic 500g,39.0,5.32,207.48
34,35,17,Organic Bananas,26.0,0.38,9.88
35,36,19,PORK RIBS FRESH FREE RANGE BY MONTANELLA 380g,18.0,4.58,82.44
36,37,19,Olive Oil 1 Liter,34.0,7.40,251.60
37,38,20,"PAMPERS BABY DRY PANTS SIZE 4 x72/Pack, 8-20kg...",28.0,4.88,136.64
38,39,20,PAMPERS SENSITIVE PROTECT WIPES PACK OF 280pcs,59.0,2.24,132.16

In [40]:
deliveries = pd.read_csv("deliveries.csv")
deliveries_clean = deliveries.copy()

deliveries_clean["delivery_status"] = (
    deliveries_clean["delivery_status"]
    .astype("string")
    .str.strip()
    .str.upper()
)

deliveries_clean["delivery_time"] = pd.to_datetime(
    deliveries_clean["delivery_time"],
    errors="coerce"
)

po_store_lookup = pd.read_sql(
    """
    SELECT purchase_order_id, store_id AS purchase_order_store_id
    FROM purchase_orders;
    """,
    pg_engine
)

delivery_check = deliveries_clean.merge(
    po_store_lookup,
    on="purchase_order_id",
    how="left"
)

assert deliveries_clean["delivery_id"].notna().all()
assert deliveries_clean["delivery_id"].is_unique
assert delivery_check["purchase_order_store_id"].notna().all()
assert deliveries_clean["delivery_time"].notna().all()

# A delivery must go to the same store as its purchase order
assert (
    delivery_check["store_id"]
    == delivery_check["purchase_order_store_id"]
).all()

assert deliveries_clean["delivery_status"].isin({
    "PENDING", "IN_TRANSIT", "PARTIALLY_RECEIVED",
    "RECEIVED", "REJECTED", "CANCELLED"
}).all()

deliveries_clean.to_sql(
    "deliveries",
    pg_engine,
    if_exists="append",
    index=False,
    method="multi"
)

print(f"{len(deliveries_clean)} deliveries loaded into PostgreSQL.")

20 deliveries loaded into PostgreSQL.

In [41]:
pd.read_sql(
    """
    SELECT d.delivery_id, d.purchase_order_id, s.store_name,
           d.delivery_time, d.delivery_status
    FROM deliveries d
    JOIN stores s ON d.store_id = s.store_id
    ORDER BY d.delivery_id;
    """,
    pg_engine
)

,delivery_id,purchase_order_id,store_name,delivery_time,delivery_status
0,1,1,ABC Foodmart - Jackson Heights,2026-05-10 08:30:00,RECEIVED
1,2,2,ABC Foodmart - Astoria,2026-05-14 08:30:00,PARTIALLY_RECEIVED
2,3,3,ABC Foodmart - Jackson Heights,2026-05-18 08:30:00,PENDING
3,4,4,ABC Foodmart - Astoria,2026-05-22 08:30:00,RECEIVED
4,5,5,ABC Foodmart - Jackson Heights,2026-05-26 08:30:00,RECEIVED
5,6,6,ABC Foodmart - Astoria,2026-05-30 08:30:00,PARTIALLY_RECEIVED
6,7,7,ABC Foodmart - Jackson Heights,2026-06-03 08:30:00,PENDING
7,8,8,ABC Foodmart - Astoria,2026-06-07 08:30:00,RECEIVED
8,9,9,ABC Foodmart - Jackson Heights,2026-06-11 08:30:00,RECEIVED
9,10,10,ABC Foodmart - Astoria,2026-06-15 08:30:00,PARTIALLY_RECEIVED
10,11,11,ABC Foodmart - Jackson Heights,2026-06-19 08:30:00,PENDING
11,12,12,ABC Foodmart - Astoria,2026-06-23 08:30:00,RECEIVED
12,13,13,ABC Foodmart - Jackson Heights,2026-06-27 08:30:00,RECEIVED
13,14,14,ABC Foodmart - Astoria,2026-07-01 08:30:00,PARTIALLY_RECEIVED
14,15,15,ABC Foodmart - Jackson Heights,2026-07-05 08:30:00,PENDING
15,16,16,ABC Foodmart - Astoria,2026-07-09 08:30:00,RECEIVED
16,17,17,ABC Foodmart - Jackson Heights,2026-07-13 08:30:00,RECEIVED
17,18,18,ABC Foodmart - Astoria,2026-07-17 08:30:00,PARTIALLY_RECEIVED
18,19,19,ABC Foodmart - Jackson Heights,2026-07-21 08:30:00,PENDING
19,20,20,ABC Foodmart - Astoria,2026-07-25 08:30:00,RECEIVED

In [42]:
promotions = pd.read_csv("promotions.csv")
promotions_clean = promotions.copy()

promotions_clean["promotion_name"] = (
    promotions_clean["promotion_name"]
    .astype("string")
    .str.strip()
)

promotions_clean["discount_type"] = (
    promotions_clean["discount_type"]
    .astype("string")
    .str.strip()
    .str.lower()
    .map({
        "percentage": "Percentage",
        "amount": "Amount"
    })
)

promotions_clean["promotion_status"] = (
    promotions_clean["promotion_status"]
    .astype("string")
    .str.strip()
    .str.lower()
    .map({
        "active": "Active",
        "inactive": "Inactive",
        "expired": "Expired"
    })
)

promotions_clean["discount_value"] = pd.to_numeric(
    promotions_clean["discount_value"],
    errors="coerce"
)

for column in ["start_date", "end_date"]:
    promotions_clean[column] = pd.to_datetime(
        promotions_clean[column],
        errors="coerce"
    )

valid_product_ids = set(
    pd.read_sql("SELECT product_id FROM products;", pg_engine)["product_id"]
)

assert promotions_clean["promotion_id"].notna().all()
assert promotions_clean["promotion_id"].is_unique
assert promotions_clean["promotion_name"].notna().all()
assert promotions_clean["discount_value"].notna().all()
assert (promotions_clean["discount_value"] >= 0).all()

# product_id is nullable in the schema, but if present, it must exist in products
has_product = promotions_clean["product_id"].notna()
assert promotions_clean.loc[has_product, "product_id"].isin(valid_product_ids).all()

assert promotions_clean["discount_type"].isin(
    {"Percentage", "Amount"}
).all()

assert (
    promotions_clean.loc[
        promotions_clean["discount_type"] == "Percentage",
        "discount_value"
    ] <= 100
).all()

assert promotions_clean["start_date"].notna().all()
assert promotions_clean["end_date"].notna().all()
assert (promotions_clean["end_date"] >= promotions_clean["start_date"]).all()

assert promotions_clean["promotion_status"].isin(
    {"Active", "Inactive", "Expired"}
).all()

for column in ["start_date", "end_date"]:
    promotions_clean[column] = promotions_clean[column].dt.date

promotions_clean.to_sql(
    "promotions",
    pg_engine,
    if_exists="append",
    index=False,
    method="multi"
)

print(f"{len(promotions_clean)} promotions loaded into PostgreSQL.")

8 promotions loaded into PostgreSQL.

In [43]:
pd.read_sql(
    """
    SELECT pr.promotion_id, pr.promotion_name, p.product_name,
           pr.discount_type, pr.discount_value,
           pr.start_date, pr.end_date, pr.promotion_status
    FROM promotions pr
    LEFT JOIN products p ON pr.product_id = p.product_id
    ORDER BY pr.promotion_id;
    """,
    pg_engine
)

,promotion_id,promotion_name,product_name,discount_type,discount_value,start_date,end_date,promotion_status
0,1,Summer Savings 1,"PAMPERS BABY DRY PANTS SIZE 4 x72/Pack, 8-20kg...",Percentage,10.0,2026-07-01,2026-08-31,Active
1,2,Summer Savings 2,PAMPERS SENSITIVE PROTECT WIPES PACK OF 280pcs,Percentage,15.0,2026-07-01,2026-08-31,Active
2,3,Summer Savings 3,Reusable Shopping Bags 5 Count,Percentage,10.0,2026-07-01,2026-08-31,Active
3,4,Summer Savings 4,Aluminum Foil 75 sq ft,Percentage,15.0,2026-07-01,2026-08-31,Active
4,5,Summer Savings 5,PORK RIBS FRESH FREE RANGE BY MONTANELLA 380g,Percentage,10.0,2026-07-01,2026-08-31,Active
5,6,Summer Savings 6,CHICKEN THIGH 400g,Percentage,15.0,2026-07-01,2026-08-31,Active
6,7,Summer Savings 7,BEEF FILLET Steak Organic 500g,Percentage,10.0,2026-07-01,2026-08-31,Active
7,8,Summer Savings 8,NATURAL WHOLE YOGURT WITH STRAWBERRIES PACK OF 6,Percentage,15.0,2026-07-01,2026-08-31,Active

In [44]:
sales = pd.read_csv("sales.csv")
sales_clean = sales.copy()

sales_clean["register_number"] = (
    sales_clean["register_number"]
    .astype("string")
    .str.strip()
)

sales_clean["payment_method"] = (
    sales_clean["payment_method"]
    .astype("string")
    .str.strip()
    .str.lower()
    .map({
        "cash": "Cash",
        "credit card": "Credit Card",
        "debit card": "Debit Card",
        "mobile payment": "Mobile Payment",
        "gift card": "Gift Card"
    })
)

sales_clean["sale_datetime"] = pd.to_datetime(
    sales_clean["sale_datetime"],
    errors="coerce"
)

for column in ["payment_amount", "total_amount"]:
    sales_clean[column] = pd.to_numeric(
        sales_clean[column],
        errors="coerce"
    )

valid_store_ids = set(
    pd.read_sql("SELECT store_id FROM stores;", pg_engine)["store_id"]
)

valid_customer_ids = set(
    pd.read_sql("SELECT customer_id FROM customers;", pg_engine)["customer_id"]
)

assert sales_clean["sale_id"].notna().all()
assert sales_clean["sale_id"].is_unique
assert sales_clean["store_id"].isin(valid_store_ids).all()

has_customer = sales_clean["customer_id"].notna()
assert sales_clean.loc[has_customer, "customer_id"].isin(
    valid_customer_ids
).all()

assert sales_clean["sale_datetime"].notna().all()
assert sales_clean["payment_method"].isin({
    "Cash", "Credit Card", "Debit Card",
    "Mobile Payment", "Gift Card"
}).all()

assert sales_clean["payment_amount"].notna().all()
assert sales_clean["total_amount"].notna().all()
assert (sales_clean["payment_amount"] >= 0).all()
assert (sales_clean["total_amount"] >= 0).all()

# One-payment transaction: paid amount should equal the sale total
assert np.isclose(
    sales_clean["payment_amount"],
    sales_clean["total_amount"],
    atol=0.01
).all()

sales_clean.to_sql(
    "sales",
    pg_engine,
    if_exists="append",
    index=False,
    method="multi"
)

print(f"{len(sales_clean)} sales loaded into PostgreSQL.")

200 sales loaded into PostgreSQL.

In [45]:
pd.read_sql(
    """
    SELECT sale_id, sale_datetime, store_id, customer_id,
           payment_method, payment_amount, total_amount
    FROM sales
    ORDER BY sale_id;
    """,
    pg_engine
).head(10)

,sale_id,sale_datetime,store_id,customer_id,payment_method,payment_amount,total_amount
0,1,2026-07-01 03:00:00,1,8,Credit Card,13.35,13.35
1,2,2026-07-01 06:00:00,2,15,Debit Card,43.17,43.17
2,3,2026-07-01 09:00:00,1,22,Mobile Payment,1.50,1.50
3,4,2026-07-01 12:00:00,2,29,Cash,39.35,39.35
4,5,2026-07-01 15:00:00,1,36,Credit Card,20.34,20.34
5,6,2026-07-01 18:00:00,2,43,Debit Card,5.49,5.49
6,7,2026-07-01 21:00:00,1,50,Mobile Payment,33.45,33.45
7,8,2026-07-02 00:00:00,2,57,Cash,42.05,42.05
8,9,2026-07-02 03:00:00,1,64,Credit Card,4.79,4.79
9,10,2026-07-02 06:00:00,2,71,Debit Card,31.98,31.98

In [47]:
with pg_engine.begin() as conn:
    existing_rows = conn.execute(
        text("SELECT COUNT(*) FROM sale_items;")
    ).scalar()

    if existing_rows != 0:
        raise ValueError(
            "sale_items already has data. Stop and tell me before continuing."
        )

    conn.execute(text(
        "ALTER TABLE sale_items "
        "ADD COLUMN IF NOT EXISTS unit_cost_at_sale DECIMAL(10,2) "
        "CHECK (unit_cost_at_sale >= 0);"
    ))

    conn.execute(text(
        "ALTER TABLE sale_items "
        "ALTER COLUMN unit_cost_at_sale SET NOT NULL;"
    ))

print("sale_items is ready for cost enrichment.")

sale_items is ready for cost enrichment.

In [48]:
import numpy as np

sale_items = pd.read_csv("sale_items.csv")
sale_items_clean = sale_items.copy()

for column in [
    "sale_item_id", "sale_id", "product_id",
    "promotion_id", "quantity"
]:
    sale_items_clean[column] = pd.to_numeric(
        sale_items_clean[column],
        errors="coerce"
    ).astype("Int64")

for column in ["unit_price", "discount_amount", "line_total"]:
    sale_items_clean[column] = pd.to_numeric(
        sale_items_clean[column],
        errors="coerce"
    )

valid_sale_ids = set(
    pd.read_sql("SELECT sale_id FROM sales;", pg_engine)["sale_id"]
)

valid_product_ids = set(
    pd.read_sql("SELECT product_id FROM products;", pg_engine)["product_id"]
)

valid_promotion_ids = set(
    pd.read_sql(
        "SELECT promotion_id FROM promotions;",
        pg_engine
    )["promotion_id"]
)

assert sale_items_clean["sale_item_id"].notna().all()
assert sale_items_clean["sale_item_id"].is_unique
assert sale_items_clean["sale_id"].isin(valid_sale_ids).all()
assert sale_items_clean["product_id"].isin(valid_product_ids).all()

has_promotion = sale_items_clean["promotion_id"].notna()
assert sale_items_clean.loc[
    has_promotion, "promotion_id"
].isin(valid_promotion_ids).all()

assert (sale_items_clean["quantity"] > 0).all()
assert (sale_items_clean["unit_price"] >= 0).all()
assert (sale_items_clean["discount_amount"] >= 0).all()
assert (sale_items_clean["line_total"] >= 0).all()

assert np.isclose(
    sale_items_clean["line_total"],
    sale_items_clean["quantity"] * sale_items_clean["unit_price"]
    - sale_items_clean["discount_amount"],
    atol=0.01
).all()

print("Sale-items validation passed.")

Sale-items validation passed.

In [49]:
sales_lookup = pd.read_sql(
    "SELECT sale_id, sale_datetime FROM sales;",
    pg_engine
)
sales_lookup["sale_datetime"] = pd.to_datetime(
    sales_lookup["sale_datetime"]
)

products_lookup = pd.read_sql(
    "SELECT product_id, category, selling_price FROM products;",
    pg_engine
)

po_cost_history = pd.read_sql(
    "SELECT poi.purchase_order_id, poi.product_id, poi.unit_cost, "
    "po.order_date, po.order_status "
    "FROM purchase_order_items poi "
    "JOIN purchase_orders po "
    "ON poi.purchase_order_id = po.purchase_order_id "
    "WHERE po.order_status IN ('RECEIVED', 'PARTIALLY_RECEIVED');",
    pg_engine
)

po_cost_history["order_date"] = pd.to_datetime(
    po_cost_history["order_date"]
)

sale_items_enriched = (
    sale_items_clean
    .merge(sales_lookup, on="sale_id", how="left")
    .merge(products_lookup, on="product_id", how="left")
)

cost_candidates = (
    sale_items_enriched[
        ["sale_item_id", "product_id", "sale_datetime"]
    ]
    .merge(po_cost_history, on="product_id", how="left")
)

prior_cost_candidates = cost_candidates[
    cost_candidates["order_date"] <= cost_candidates["sale_datetime"]
]

latest_purchase_cost = (
    prior_cost_candidates
    .sort_values(["sale_item_id", "order_date", "purchase_order_id"])
    .groupby("sale_item_id", group_keys=False)
    .tail(1)[["sale_item_id", "unit_cost"]]
    .rename(columns={"unit_cost": "purchase_history_cost"})
)

sale_items_enriched = sale_items_enriched.merge(
    latest_purchase_cost,
    on="sale_item_id",
    how="left"
)

cost_reference = po_cost_history.merge(
    products_lookup,
    on="product_id",
    how="left"
)

cost_reference["cost_ratio"] = (
    cost_reference["unit_cost"] / cost_reference["selling_price"]
)

category_cost_rate = (
    cost_reference.groupby("category")["cost_ratio"].mean()
)

overall_cost_rate = cost_reference["cost_ratio"].mean()

sale_items_enriched["unit_cost_at_sale"] = (
    sale_items_enriched["purchase_history_cost"]
)

sale_items_enriched["cost_source"] = np.where(
    sale_items_enriched["purchase_history_cost"].notna(),
    "Purchase history",
    pd.NA
)

missing_cost = sale_items_enriched["unit_cost_at_sale"].isna()

sale_items_enriched["category_cost_rate"] = (
    sale_items_enriched["category"].map(category_cost_rate)
)

use_category_estimate = (
    missing_cost
    & sale_items_enriched["category_cost_rate"].notna()
)

use_overall_estimate = (
    missing_cost
    & sale_items_enriched["category_cost_rate"].isna()
)

sale_items_enriched.loc[missing_cost, "unit_cost_at_sale"] = (
    sale_items_enriched.loc[missing_cost, "selling_price"]
    * sale_items_enriched.loc[missing_cost, "category_cost_rate"]
    .fillna(overall_cost_rate)
)

sale_items_enriched.loc[
    use_category_estimate, "cost_source"
] = "Category estimate"

sale_items_enriched.loc[
    use_overall_estimate, "cost_source"
] = "Overall estimate"

sale_items_enriched["unit_cost_at_sale"] = (
    sale_items_enriched["unit_cost_at_sale"].round(2)
)

assert sale_items_enriched["unit_cost_at_sale"].notna().all()
assert (sale_items_enriched["unit_cost_at_sale"] >= 0).all()

cost_audit = (
    sale_items_enriched["cost_source"]
    .value_counts()
    .rename_axis("cost_source")
    .reset_index(name="sale_item_count")
)

display(cost_audit)

         cost_source  sale_item_count
0   Purchase history              186
1   Overall estimate              121
2  Category estimate               94

In [50]:
sale_items_for_pg = sale_items_enriched[
    [
        "sale_item_id",
        "sale_id",
        "product_id",
        "promotion_id",
        "quantity",
        "unit_price",
        "unit_cost_at_sale",
        "discount_amount",
        "line_total"
    ]
].copy()

# Convert pandas missing values to SQL NULL values
sale_items_for_pg = (
    sale_items_for_pg
    .astype(object)
    .where(pd.notna(sale_items_for_pg), None)
)

sale_items_for_pg.to_sql(
    "sale_items",
    pg_engine,
    if_exists="append",
    index=False,
    method="multi"
)

print(f"{len(sale_items_for_pg)} sale items loaded into PostgreSQL.")

401 sale items loaded into PostgreSQL.

In [51]:
returns = pd.read_csv("returns.csv")
returns_clean = returns.copy()

returns_clean["return_reason"] = (
    returns_clean["return_reason"]
    .astype("string")
    .str.strip()
)

returns_clean["refund_method"] = (
    returns_clean["refund_method"]
    .astype("string")
    .str.strip()
    .str.lower()
    .map({
        "cash": "Cash",
        "credit card": "Credit Card",
        "debit card": "Debit Card",
        "mobile payment": "Mobile Payment",
        "gift card": "Gift Card",
        "store credit": "Store Credit"
    })
)

returns_clean["return_status"] = (
    returns_clean["return_status"]
    .astype("string")
    .str.strip()
    .str.lower()
    .map({
        "pending": "Pending",
        "approved": "Approved",
        "rejected": "Rejected",
        "completed": "Completed"
    })
)

returns_clean["return_date"] = pd.to_datetime(
    returns_clean["return_date"],
    errors="coerce"
)

returns_clean["return_quantity"] = pd.to_numeric(
    returns_clean["return_quantity"],
    errors="coerce"
).astype("Int64")

returns_clean["refund_amount"] = pd.to_numeric(
    returns_clean["refund_amount"],
    errors="coerce"
)

sale_item_lookup = pd.read_sql(
    "SELECT si.sale_item_id, si.quantity AS sold_quantity, "
    "si.line_total, s.customer_id AS sale_customer_id "
    "FROM sale_items si "
    "JOIN sales s ON si.sale_id = s.sale_id;",
    pg_engine
)

return_check = returns_clean.merge(
    sale_item_lookup,
    on="sale_item_id",
    how="left"
)

valid_customer_ids = set(
    pd.read_sql("SELECT customer_id FROM customers;", pg_engine)["customer_id"]
)

assert returns_clean["return_id"].notna().all()
assert returns_clean["return_id"].is_unique
assert return_check["sold_quantity"].notna().all()
assert returns_clean["return_date"].notna().all()
assert (returns_clean["return_quantity"] > 0).all()
assert (returns_clean["refund_amount"] >= 0).all()

assert returns_clean["refund_method"].isin({
    "Cash", "Credit Card", "Debit Card",
    "Mobile Payment", "Gift Card", "Store Credit"
}).all()

assert returns_clean["return_status"].isin({
    "Pending", "Approved", "Rejected", "Completed"
}).all()

# A returned quantity cannot exceed the original quantity purchased
assert (
    return_check["return_quantity"]
    <= return_check["sold_quantity"]
).all()

# If customer_id is recorded, it must match the customer from the sale
has_customer = returns_clean["customer_id"].notna()

assert returns_clean.loc[
    has_customer, "customer_id"
].isin(valid_customer_ids).all()

assert (
    return_check.loc[has_customer, "customer_id"]
    == return_check.loc[has_customer, "sale_customer_id"]
).all()

# Refund cannot exceed the proportional value of the returned item
expected_refund = (
    return_check["return_quantity"]
    * return_check["line_total"]
    / return_check["sold_quantity"]
)

assert np.isclose(
    return_check["refund_amount"],
    expected_refund,
    atol=0.01
).all()

returns_clean["return_date"] = returns_clean["return_date"].dt.date

returns_for_pg = (
    returns_clean
    .astype(object)
    .where(pd.notna(returns_clean), None)
)

returns_for_pg.to_sql(
    "returns",
    pg_engine,
    if_exists="append",
    index=False,
    method="multi"
)

print(f"{len(returns_for_pg)} returns loaded into PostgreSQL.")

20 returns loaded into PostgreSQL.

In [52]:
pd.read_sql(
    "SELECT return_id, sale_item_id, customer_id, return_date, "
    "return_quantity, refund_amount, return_status "
    "FROM returns ORDER BY return_id;",
    pg_engine
)

,return_id,sale_item_id,customer_id,return_date,return_quantity,refund_amount,return_status
0,1,1,8,2026-08-02,1,5.49,Completed
1,2,18,64,2026-08-03,1,4.79,Completed
2,3,35,40,2026-08-04,1,7.00,Completed
3,4,52,23,2026-08-05,1,6.99,Completed
4,5,69,6,2026-08-06,1,1.29,Completed
5,6,86,62,2026-08-07,1,12.99,Completed
6,7,103,45,2026-08-08,1,9.27,Completed
7,8,120,21,2026-08-09,1,8.99,Completed
8,9,137,77,2026-08-10,1,5.00,Completed
9,10,154,60,2026-08-11,1,3.49,Completed
10,11,171,43,2026-08-12,1,5.49,Completed
11,12,188,19,2026-08-13,1,9.99,Completed
12,13,205,2,2026-08-14,1,1.50,Completed
13,14,222,58,2026-08-15,1,5.49,Completed
14,15,239,34,2026-08-16,1,1.49,Completed
15,16,256,17,2026-08-17,1,3.58,Completed
16,17,273,80,2026-08-18,1,11.49,Completed
17,18,290,56,2026-08-19,1,3.49,Completed
18,19,307,39,2026-08-20,1,4.69,Completed
19,20,324,15,2026-08-21,1,10.30,Completed

In [54]:
inventory = pd.read_csv("inventory.csv")
inventory_check = inventory.copy()

inventory_check["last_updated_at"] = pd.to_datetime(
    inventory_check["last_updated_at"],
    errors="coerce"
)

store_lookup = pd.read_sql(
    "SELECT store_id, store_name, opening_date, store_status FROM stores;",
    pg_engine
)

store_lookup["opening_date"] = pd.to_datetime(
    store_lookup["opening_date"]
)

inventory_check = inventory_check.merge(
    store_lookup,
    on="store_id",
    how="left"
)

inventory_summary = (
    inventory_check
    .groupby(["store_id", "store_name", "store_status"], dropna=False)
    .agg(
        inventory_rows=("inventory_id", "count"),
        total_quantity_on_hand=("quantity_on_hand", "sum"),
        last_inventory_update=("last_updated_at", "max"),
        store_opening_date=("opening_date", "first")
    )
    .reset_index()
)

display(inventory_summary)

,store_id,store_name,store_status,inventory_rows,total_quantity_on_hand,last_inventory_update,store_opening_date
0,1,ABC Foodmart - Jackson Heights,Active,30,1727,2026-08-12 09:00:00,1996-04-15
1,2,ABC Foodmart - Astoria,Active,30,1341,2026-08-12 09:00:00,2004-09-01
2,3,ABC Foodmart - Williamsburg,Planned,30,0,2026-08-12 09:00:00,2027-03-01
3,4,ABC Foodmart - Crown Heights,Planned,30,0,2026-08-12 09:00:00,2027-06-01
4,5,ABC Foodmart - Bay Ridge,Planned,30,0,2026-08-12 09:00:00,2027-09-01

In [55]:
inventory_clean = inventory.copy()

for column in ["inventory_id", "store_id", "product_id"]:
    inventory_clean[column] = pd.to_numeric(
        inventory_clean[column],
        errors="coerce"
    ).astype("Int64")

for column in ["quantity_on_hand", "reorder_point"]:
    inventory_clean[column] = pd.to_numeric(
        inventory_clean[column],
        errors="coerce"
    )

inventory_clean["last_updated_at"] = pd.to_datetime(
    inventory_clean["last_updated_at"],
    errors="coerce"
)

store_status_lookup = pd.read_sql(
    "SELECT store_id, store_status FROM stores;",
    pg_engine
)

inventory_clean = inventory_clean.merge(
    store_status_lookup,
    on="store_id",
    how="left"
)

valid_product_ids = set(
    pd.read_sql("SELECT product_id FROM products;", pg_engine)["product_id"]
)

assert inventory_clean["inventory_id"].notna().all()
assert inventory_clean["inventory_id"].is_unique
assert inventory_clean["store_status"].notna().all()
assert inventory_clean["product_id"].isin(valid_product_ids).all()
assert inventory_clean["quantity_on_hand"].notna().all()
assert inventory_clean["reorder_point"].notna().all()
assert inventory_clean["last_updated_at"].notna().all()

assert (inventory_clean["quantity_on_hand"] >= 0).all()
assert (inventory_clean["reorder_point"] >= 0).all()

assert not inventory_clean.duplicated(
    subset=["store_id", "product_id"]
).any()

# Planned stores may have product setup records, but no physical inventory yet
planned_inventory = inventory_clean[
    inventory_clean["store_status"] == "Planned"
]

assert (planned_inventory["quantity_on_hand"] == 0).all()

inventory_for_pg = inventory_clean[
    [
        "inventory_id",
        "store_id",
        "product_id",
        "quantity_on_hand",
        "reorder_point",
        "last_updated_at"
    ]
].copy()

inventory_for_pg.to_sql(
    "inventory",
    pg_engine,
    if_exists="append",
    index=False,
    method="multi"
)

print(f"{len(inventory_for_pg)} inventory records loaded into PostgreSQL.")

150 inventory records loaded into PostgreSQL.

In [56]:
operating_expenses = pd.read_csv("operating_expenses.csv")
expenses_clean = operating_expenses.copy()

for column in ["expense_type", "description"]:
    expenses_clean[column] = (
        expenses_clean[column]
        .astype("string")
        .str.strip()
    )

expenses_clean["expense_date"] = pd.to_datetime(
    expenses_clean["expense_date"],
    errors="coerce"
)

expenses_clean["amount"] = pd.to_numeric(
    expenses_clean["amount"],
    errors="coerce"
)

expenses_clean["expense_id"] = pd.to_numeric(
    expenses_clean["expense_id"],
    errors="coerce"
).astype("Int64")

expenses_clean["store_id"] = pd.to_numeric(
    expenses_clean["store_id"],
    errors="coerce"
).astype("Int64")

store_expense_lookup = pd.read_sql(
    "SELECT store_id, store_status, opening_date FROM stores;",
    pg_engine
)

store_expense_lookup["opening_date"] = pd.to_datetime(
    store_expense_lookup["opening_date"]
)

expenses_clean = expenses_clean.merge(
    store_expense_lookup,
    on="store_id",
    how="left"
)

assert expenses_clean["expense_id"].notna().all()
assert expenses_clean["expense_id"].is_unique
assert expenses_clean["store_status"].notna().all()
assert expenses_clean["expense_date"].notna().all()
assert expenses_clean["expense_type"].notna().all()
assert expenses_clean["amount"].notna().all()
assert (expenses_clean["amount"] >= 0).all()

# Classify expenses incurred before a planned store has opened
pre_opening_mask = (
    (expenses_clean["store_status"] == "Planned")
    & (expenses_clean["expense_date"] < expenses_clean["opening_date"])
)

expenses_clean.loc[pre_opening_mask, "expense_type"] = (
    "Pre-Opening "
    + expenses_clean.loc[pre_opening_mask, "expense_type"]
)

print(
    f"{pre_opening_mask.sum()} expense records classified as pre-opening expenses."
)

expenses_for_pg = expenses_clean[
    [
        "expense_id",
        "store_id",
        "expense_date",
        "expense_type",
        "amount",
        "description"
    ]
].copy()

expenses_for_pg["expense_date"] = expenses_for_pg["expense_date"].dt.date

expenses_for_pg = (
    expenses_for_pg
    .astype(object)
    .where(pd.notna(expenses_for_pg), None)
)

expenses_for_pg.to_sql(
    "operating_expenses",
    pg_engine,
    if_exists="append",
    index=False,
    method="multi"
)

print(f"{len(expenses_for_pg)} expenses loaded into PostgreSQL.")

24 expense records classified as pre-opening expenses.
40 expenses loaded into PostgreSQL.

In [57]:
pd.read_sql(
    "SELECT s.store_name, s.store_status, oe.expense_type, "
    "ROUND(SUM(oe.amount), 2) AS total_expense "
    "FROM operating_expenses oe "
    "JOIN stores s ON oe.store_id = s.store_id "
    "GROUP BY s.store_name, s.store_status, oe.expense_type "
    "ORDER BY s.store_name, oe.expense_type;",
    pg_engine
)

,store_name,store_status,expense_type,total_expense
0,ABC Foodmart - Astoria,Active,Rent,66000.0
1,ABC Foodmart - Astoria,Active,Utilities,9760.0
2,ABC Foodmart - Bay Ridge,Planned,Pre-Opening Rent,75000.0
3,ABC Foodmart - Bay Ridge,Planned,Pre-Opening Utilities,11200.0
4,ABC Foodmart - Crown Heights,Planned,Pre-Opening Rent,72000.0
5,ABC Foodmart - Crown Heights,Planned,Pre-Opening Utilities,10720.0
6,ABC Foodmart - Jackson Heights,Active,Rent,63000.0
7,ABC Foodmart - Jackson Heights,Active,Utilities,9280.0
8,ABC Foodmart - Williamsburg,Planned,Pre-Opening Rent,69000.0
9,ABC Foodmart - Williamsburg,Planned,Pre-Opening Utilities,10240.0

In [58]:
expected_counts = {
    "stores": 5,
    "positions": 6,
    "vendors": 7,
    "customers": 500,
    "departments": 20,
    "products": 30,
    "employees": 50,
    "employee_shifts": 100,
    "time_off_records": 10,
    "operating_expenses": 40,
    "inventory": 150,
    "purchase_orders": 20,
    "purchase_order_items": 39,
    "deliveries": 20,
    "promotions": 8,
    "sales": 200,
    "sale_items": 401,
    "returns": 20
}

table_counts = []

with pg_engine.connect() as conn:
    for table_name, expected_count in expected_counts.items():
        actual_count = conn.execute(
            text(f"SELECT COUNT(*) FROM {table_name};")
        ).scalar()

        table_counts.append({
            "table_name": table_name,
            "expected_rows": expected_count,
            "actual_rows": actual_count,
            "passed": actual_count == expected_count
        })

table_counts = pd.DataFrame(table_counts)

display(table_counts)

assert table_counts["passed"].all()

print("All 18 PostgreSQL tables passed the ETL row-count check.")

              table_name  expected_rows  actual_rows  passed
0                 stores              5            5    True
1              positions              6            6    True
2                vendors              7            7    True
3              customers            500          500    True
4            departments             20           20    True
5               products             30           30    True
6              employees             50           50    True
7        employee_shifts            100          100    True
8       time_off_records             10           10    True
9     operating_expenses             40           40    True
10             inventory            150          150    True
11       purchase_orders             20           20    True
12  purchase_order_items             39           39    True
13            deliveries             20           20    True
14            promotions              8            8    True
15                 sales            200          200    True
16            sale_items            401          401    True
17               returns             20           20    True

All 18 PostgreSQL tables passed the ETL row-count check.